Display command return code in user interface

diff --git a/data/Startup/bash_startup.in b/data/Startup/bash_startup.in
--- a/data/Startup/bash_startup.in
+++ b/data/Startup/bash_startup.in
@@ -33,6 +33,12 @@ export -f send_control_sequence
 
 # Logic for prompt and command detection
 
+function send_return_code() {
+	# Send sequence containing the return code of the last command
+	send_control_sequence "$(final_term_control_sequence 'D' "$?")"
+}
+PROMPT_COMMAND=send_return_code;$PROMPT_COMMAND
+
 precmd() {
 	# Send sequence marking a command prompt
 	send_control_sequence "$(final_term_control_sequence 'A')"
@@ -54,17 +60,17 @@ PS1=$PS1$(final_term_control_sequence 'B')
 function text_menu_start() {
 	# NOTE: Nested double quotes look strange, but are both valid and necessary;
 	#       see http://stackoverflow.com/questions/4031007
-	echo "$(final_term_control_sequence 'D' "$1")"
+	echo "$(final_term_control_sequence 'E' "$1")"
 }
 export -f text_menu_start
 
 function text_menu_end() {
-	echo "$(final_term_control_sequence 'E' "$1")"
+	echo "$(final_term_control_sequence 'F' "$1")"
 }
 export -f text_menu_end
 
 function send_progress() {
-	send_control_sequence "$(final_term_control_sequence 'F' "$1" "$2")"
+	send_control_sequence "$(final_term_control_sequence 'G' "$1" "$2")"
 }
 export -f send_progress
 
